### ISSUE TITLE
Ktor 3 compatibility

### ISSUE THREAD

**Issue by sschuberth** [SMILEY4/ktor-openapi-tools#136]
Although there are [no official release notes](https://github.com/ktorio/ktor/releases) yet, Ktor 3.0.0 final was published and tools like Renovate and Dependabot start updating projects to it.

During that upgrade, our project tests now [fail with](https://github.com/eclipse-apoapsis/ort-server/actions/runs/11259267196/job/31307842354?pr=1188#step:5:246)

```
     java.lang.IncompatibleClassChangeError: Found interface io.ktor.server.routing.Route, but class was expected
        at io.github.smiley4.ktorswaggerui.dsl.routing.DocumentedRouteSelectorKt.documentation(DocumentedRouteSelector.kt:41)
        at io.github.smiley4.ktorswaggerui.dsl.routing.DocumentedRouteSelectorKt.get(DocumentedRouteSelector.kt:99)
        at org.eclipse.apoapsis.ortserver.core.api.HealthKt.healthChecks(Health.kt:30)
        at org.eclipse.apoapsis.ortserver.core.plugins.RoutingKt.configureRouting$lambda$2$lambda$1(Routing.kt:39)
        at io.ktor.server.routing.RoutingBuilderKt.route(RoutingBuilder.kt:21)
```

So looks like this project is affected by some breaking changes in Ktor 3.

**Comment by ShiinaKin** [comment]
same, they must have made some breaking changes

**Comment by sschuberth** [comment]
For reference: https://blog.jetbrains.com/kotlin/2024/10/ktor-3-0/

**Comment by piashcse** [comment]
Waiting for this [Ktor 3 compatibility](https://github.com/SMILEY4/ktor-swagger-ui/issues/136#top)

I'm using this library at https://github.com/piashcse/ktor-E-Commerce
